name: Run Bg Road Fines Serverless on Schedule

on:
  schedule:
    - cron: "*/1 * * * *" # Runs on Monday and Thursday at 18:00 UTC
  workflow_dispatch: # (optional) allows manual trigger from UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # or whichever version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # or skip if not needed

      - name: Run script
        env:
          ID_CARD: ${{ secrets.ID_CARD }}
          DRIVING_LICENSE: ${{ secrets.DRIVING_LICENSE }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          E_USLUGI_MVR: ${{ secrets.E_USLUGI_MVR }}
        run: |
          python main.py
