name: Run Bg Road Fines Serverless on Schedule

on:
  schedule:
    - cron: "0 18 * * 1,4" # Runs on Monday and Thursday at 18:00 UTC
  workflow_dispatch: # (optional) allows manual trigger from UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # or whichever version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # or skip if not needed

      - name: Run script
        run: python main.py
